version: "3.9"

services:
  api:
    build: .
    volumes:
      - ./utility:/code
    ports:
      - "8000:8000"
    depends_on:
      - ecom-db

  ecom-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
